/// <reference types="react-scripts" />

// *IMPORTANT! This allows us to interact with the most current version of browser's window api's ethereum property generated by the MetaMask extention
interface Window{
    ethereum: any;
}